server.port=9453
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=InfluencerBookingDB
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.servlet.session.timeout=30m
spring.main.allow-bean-definition-overriding=true

vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmnCode=SIS8ACPU
vnpay.hashSecret=PKQCVSGLRUNJLZBSVOQREXNIKZHWPTMW
vnpay.returnUrl=http://localhost:8080/profile/vnpay-return
